# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f3394b0cc0ac3b1d523b818f5232c9ef5929096ca0236a8ea8a8363f2eef10f4ea5f490b881d031309390c78c961e30ce98dfe8d7da45529cab43d3ca8efdae

test:
  secret_key_base: df5efcdd1f90ba62e4cba8dc9a8f6960af5abee7ceb66dc34450501745fa4bb499faf93ecbe864cfc99f504955b5f5b53ebd36df3de1758368f7daf170c1b117

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
